- name: deploy vcenter appliance
  hosts: all
  gather_facts: no
  become: no
  vars:
    network_share: 192.168.1.103:/mnt/vault/work/install
    vcenter_netmask: 255.255.255.0
    vcenter_gateway: 192.168.1.254
    vcenter_net_prefix: 24
    network_mount_dir: '{{ playbook_dir }}/mnt/net'
    iso_mount_dir: '{{ playbook_dir }}/mnt/iso'

  pre_tasks:
    - name: ensure the mount directory exists
      file:
        path: '{{ network_mount_dir }}'
        state: directory
        mode: 0755
      delegate_to: localhost

    - name: mount network share
      mount:
        path: '{{ network_mount_dir }}'
        src: '{{ network_share }}'
        fstype: nfs
        opts: nolock
        state: mounted
      delegate_to: localhost
      become: yes

  roles:
    - role: vcsa-deploy-via-linux-host
      delegate_to: localhost

  post_tasks:
    - name: unmount network share
      mount:
        path: '{{ network_mount_dir }}'
        state: unmounted
      delegate_to: localhost
      become: yes

    - name: ensure the mount directory doesn't exist
      file:
        path: '{{ network_mount_dir }}'
        state: absent
      delegate_to: localhost